/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      colors: {
        // ── Stitch design tokens ──────────────────────────────────────
        'surface':                  '#101419',
        'surface-dim':              '#101419',
        'surface-bright':           '#36393f',
        'surface-container-lowest': '#0b0e13',
        'surface-container-low':    '#191c21',
        'surface-container':        '#1d2025',
        'surface-container-high':   '#272a30',
        'surface-container-highest':'#32353b',
        'on-surface':               '#e1e2e9',
        'on-surface-variant':       '#c1c7d3',
        'inverse-surface':          '#e1e2e9',
        'inverse-on-surface':       '#2d3036',
        'outline':                  '#8b919d',
        'outline-variant':          '#414751',
        'surface-tint':             '#a4c9ff',
        'primary':                  '#a4c9ff',
        'on-primary':               '#00315d',
        'primary-container':        '#60a5fa',
        'on-primary-container':     '#003a6b',
        'inverse-primary':          '#0060ac',
        'secondary':                '#45dfa4',
        'on-secondary':             '#003825',
        'secondary-container':      '#00bd85',
        'on-secondary-container':   '#00452e',
        'tertiary':                 '#fabd34',
        'on-tertiary':              '#412d00',
        'tertiary-container':       '#d19900',
        'on-tertiary-container':    '#4b3500',
        'error':                    '#ffb4ab',
        'on-error':                 '#690005',
        'error-container':          '#93000a',
        'on-error-container':       '#ffdad6',
        // ── Status semantics ──────────────────────────────────────────
        safe:     { DEFAULT: '#45dfa4', light: '#bbf7d0', dark: '#15803d' },
        elevated: { DEFAULT: '#fabd34', light: '#fef9c3', dark: '#a16207' },
        high:     { DEFAULT: '#f97316', light: '#ffedd5', dark: '#c2410c' },
        critical: { DEFAULT: '#ffb4ab', light: '#fee2e2', dark: '#93000a' },
        // ── Legacy surface tokens kept for component compat ───────────
        'surface-card':   '#1d2025',
        'surface-border': '#414751',
        'surface-muted':  '#8b919d',
      },
      fontSize: {
        'label-sm':       ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'title-lg':       ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'title-lg-mobile':['24px', { lineHeight: '32px', fontWeight: '500' }],
        'section-header': ['17px', { lineHeight: '24px', letterSpacing: '0.05em', fontWeight: '600' }],
        'metric-lg':      ['72px', { lineHeight: '80px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'metric-display': ['96px', { lineHeight: '100px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-main':      ['15px', { lineHeight: '22px', fontWeight: '400' }],
      },
      animation: {
        'pulse-slow':     'pulse 3s cubic-bezier(0.4,0,0.6,1) infinite',
        'fade-in':        'fadeIn 0.4s ease-out',
        'slide-up':       'slideUp 0.3s ease-out',
        'glow-critical':  'glowCritical 2s ease-in-out infinite',
        'glow-high':      'glowHigh 2.5s ease-in-out infinite',
      },
      keyframes: {
        fadeIn:       { from: { opacity: '0' },                               to: { opacity: '1' } },
        slideUp:      { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        glowCritical: { '0%,100%': { boxShadow: '0 0 8px rgba(255,180,171,0.3)' }, '50%': { boxShadow: '0 0 24px rgba(255,180,171,0.6)' } },
        glowHigh:     { '0%,100%': { boxShadow: '0 0 8px rgba(249,115,22,0.3)'  }, '50%': { boxShadow: '0 0 18px rgba(249,115,22,0.6)'  } },
      },
    },
  },
  plugins: [],
}
